#!/bin/sh
tmux new -s term2x3 -d
tmux split-window -h
tmux split-window -h
tmux select-layout even-horizontal
tmux split-window
tmux select-pane -t 2
tmux split-window
tmux select-pane -t 1
tmux split-window
tmux select-pane -t 1
tmux attach-session -t term2x3
